# Generated by Django 5.1 on 2024-08-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovielist',
            name='movieId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
