# Generated by Django 5.1 on 2024-08-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_favoritemovielist_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovielist',
            name='movieId',
            field=models.IntegerField(blank=True),
        ),
    ]
