# Generated by Django 5.1 on 2024-08-31 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_favoritemovielist_movieid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovielist',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='favoritemovielist',
            name='description',
        ),
        migrations.AddField(
            model_name='favoritemovielist',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='favoritemovielist',
            name='release_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
