# Use Python 3.13
FROM python:3.13.2-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy project files
COPY . .

# Collect static files (even if unused now, it’s good for future readiness)
RUN python manage.py collectstatic --noinput || true

# Run the app using Gunicorn
CMD sh -c  "
        python manage.py migrate &&
        python manage.py createsuperuser --noinput || true &&
        gunicorn MovieAppAPI.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "